version: "3.6"
services:
  db:
    image: "postgres:14-alpine"
    environment:
      POSTGRES_DB: "trading"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"

  test_db:
    image: "postgres:14-alpine"
    environment:
      POSTGRES_DB: "trading"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "6000:5432"

  redis:
    container_name: secretary-redis
    image: "redis:7.2.2"
    ports:
      - "6379:6379"

networks:
  default:
    driver: bridge