[tool.poetry]
name = "trad"
version = "0.1.0"
description = ""
authors = ["alexe0110"]

[tool.poetry.dependencies]
python = "3.11"
fastapi = "^0.95.0"
pydantic = "^1.10.7"
uvicorn = "^0.21.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
