test_name: Test Hello API

stages:
  - name: Hello Alex test
    request:
      url: http://localhost:8000/?name=Alex
      method: GET
    response:
      status_code: 200

  - name: Add trade
    request:
      url: http://localhost:8000/trades
      json:
        - id: 123
          user_id: 887
          currency: RUB
          side: left
          price: 100.0
          amount: 10.2
      method: POST
    response:
      status_code: 200